# Generated by Django 4.1.2 on 2022-10-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btest_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_code', models.IntegerField(default='62EXBG88ESMN19ZSM6ZZ6XWZZDDHSRUU', unique=True)),
                ('customer_name', models.CharField(max_length=80)),
                ('Command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regular_P', models.FloatField()),
                ('Suray', models.FloatField()),
                ('Pump_P', models.FloatField()),
                ('is_show', models.BooleanField()),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btech_reportform.btest_case')),
            ],
        ),
    ]
