# Generated by Django 4.1.2 on 2022-10-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech_reportform', '0002_alter_btest_case_case_code_alter_btest_case_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btest_case',
            name='Case_code',
            field=models.CharField(default='FK2OWNIPPKTRNL781U8JT9CJWDA9UAPG', max_length=40, unique=True),
        ),
    ]
