# Generated by Django 4.1.2 on 2022-10-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech_reportform', '0003_alter_btest_case_case_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btest_case',
            name='Case_code',
            field=models.CharField(default='2CMYLV6HIOT828V56SP9W4UIPAFJTOJC', max_length=40, unique=True),
        ),
    ]
