# Generated by Django 4.1.2 on 2022-10-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech_reportform', '0004_alter_btest_case_case_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btest_case',
            name='Case_code',
            field=models.CharField(default='9OVCT94WDSD7K5983A56EFKGJH13SEO8', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='btest_case',
            name='Command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
