# Generated by Django 4.1.2 on 2022-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech_reportform', '0005_alter_btest_case_case_code_alter_btest_case_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_data',
            name='No',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btest_case',
            name='Case_code',
            field=models.CharField(default='DLONWON7RV3KYN9YV8WRVMJS8O1PMQWJ', max_length=40, unique=True),
        ),
    ]
